const countries = {
    "Albania":"AL",
    "Austria": "AT",
    "Belarus":"BY",
    "Belgium":"BE",
    "Bosnia Herzegovina":"BA",
    "Bulgaria":"BG",
    "Croatia":"HR",
    "Cyprus":"CY",
    "Czech Republic":"CZ",
    "Denmark":"DK",
    "Estonia":"EE",
    "Finland":"FI",
    "France":"FR",
    "Georgia":"GE",
    "Germany":"DE",
    "Greece":"GR",
    "Hungary":"HU",
    "Ireland":"IE",
    "Italy":"IT",
    "Latvia":"LV",
    "Lithuania":"LT",
    "Luxembourg":"LU",
    "Malta":"MT",
    "Montenegro":"ME",
    "Netherlands":"NL",
    "North Macedonia":"MK",
    "Norway":"NO",
    "Poland":"PL",
    "Portugal":"PT",
    "Republic of Moldova":"MD",
    "Romania":"RO",
    "Serbia":"RS",
    "Slovakia":"SK",
    "Slovenia":"SI",
    "Spain":"ES",
    "Sweden":"SE",
    "Switzerland":"CH",
    "Turkey":"TR",
    "Ukraine":"UA",
    "United Kingdom":"GB",
    "Russia":"RU",
    "Armenia": "AM",
    "Azerbaijan":"AZ",
    "Kosovo":"XK"

}
module.exports = countries
